### ISSUE TITLE
Rename column from 'email' to 'Google Apps Account' on Student Accounts gsheet feed

### ISSUE THREAD

**Issue by ldesimon** [TEAMSchools/gabby#13]
https://github.com/TEAMSchools/gabby/blob/master/extracts/v_extracts.gapps_users_students.sql

Line 17 proposed edit: 
`,acct.student_web_id + '@teamstudents.org' AS 'google apps account'`

Reason: Want to avoid additional tickets/questions when staff view the gsheet student accounts master so that "email" column is renamed "Google Apps Account" (https://docs.google.com/spreadsheets/d/1ubmCOotL3Y1WmL9l_ajBNpUTLXp6MEodZBXnDk3IFNQ/edit#gid=997992484)

Not urgent - need by 10/6

**Comment by cbini** [comment]
That's the one for GAM script, but here it's called `student_email`
https://github.com/TEAMSchools/gabby/blob/b9c4ba2b9c52be35d4c5c5717fc6a569f12caa69/extracts/v_extracts.gsheets_student_logins.sql#L15

The Google Sheet is just aliased as "Email" so you can update on the formula.
