### ISSUE TITLE
Change Clever Period for 'Enroll' Sections

### ISSUE THREAD

**Issue by ldesimon** [TEAMSchools/gabby#60]
https://github.com/TEAMSchools/gabby/blob/d2f0c7ac1527f09e2a5fe7a42bff281ca1394b9c/extracts/v_extracts.clever_sections.sql#L83

For Line 83, please replace with the following to all each section to display with a period that matches to grade level. Clever/Apps are only displaying the [Period] and each of the Enroll sections  = 1(A)

, CASE WHEN grade = 'Kindergarten' THEN '0(A)'
            WHEN grade = 1 THEN '1(A)'
            WHEN grade = 2 THEN '2(A)'
            WHEN grade = 3 THEN '3(A)'
            WHEN grade = 4 THEN '4(A)'
            WHEN grade = 5 THEN '5(A)'
            WHEN grade = 6 THEN '6(A)'
            WHEN grade = 7 THEN '7(A)'
            WHEN grade = 8 THEN '8(A)'
            WHEN grade = 9 THEN '9(A)'
            WHEN grade = 10 THEN '10(A)'
            WHEN grade = 11 THEN '11(A)'
            WHEN grade = 12 THEN '12(A)'
       ELSE '1(A)' END AS [Period]

**Comment by cbini** [comment]
fixed
